In [1]:
import numpy as np
from sklearn.metrics import precision_recall_fscore_support

In [2]:
y_true = np.array(['cat', 'dog', 'pig', 'cat', 'dog', 'pig'])
y_pred = np.array(['cat', 'pig', 'dog', 'cat', 'cat', 'dog'])

In [3]:
precision_recall_fscore_support(y_true, y_pred)

(array([0.66666667, 0.        , 0.        ]),
 array([1., 0., 0.]),
 array([0.8, 0. , 0. ]),
 array([2, 2, 2], dtype=int64))